version: "3.7"
services:
    whoami:
        image: whoami:1803-latest
        build:
            context: .
            args:
                buildimagetag: 2.1-sdk-nanoserver-1803
                runtimeimagetag: 2.1-aspnetcore-runtime-nanoserver-1803
        isolation: hyperv
