version: '3.2'
services:
   appinsights:
      build:
        context: .
      image: artisticcheese/appinsights:latest
      environment: 
        - "SHELL=powershell.exe"
      ports:
        - "80"
      networks: 
        - nat
networks: 
  nat:
    external: true